#!/usr/bin/tclsh

source ./spp_client.tcl
source ./spp_server.tcl
source ./device.tcl
source ./drivers.tcl
source ./chan.tcl
source ./locking.tcl

Device leak_ag

## Commands from the manual which do not work:
# ?CALINTOK ?INTERNAL-TYPE {?I/O BOARD} ?I/O_VER ?NOLOCAL-VMAXOUT
# 1REJECTP 2REJECTP 3REJECTP 4REJECTP
# ?STDLK-GAIN ?SYS-GAIN ?TC-GAUGE ?TUNEOK WHYNOCAL-INT

foreach c {*IDN? ?ALL ?AZ<0 ?CALOK ?CPLOCKOUT ?CURRDATE\
           ?DISPLAY ?EMISSION ?EXPONENT ?EXTLEAK ?FIL1HOURS ?FIL2HOURS\
           ?GAIN  ?INTEXT ?IONCHAMBER\
           ?LANGUAGE ?LEAK ?LKEXPIRE ?LEAKTEMP ?LP ?LPV ?LPVR ?LPVRM\
           ?LPVRJG ?LPVRJGC ?LPVRJGCTbTpV ?OFFSET\
           ?PREHEAT ?PREHEAT-TIME ?PRESSURES ?PWDONOFF ?RANGE\
           ?AREJECT ?1REJECT ?2REJECT ?3REJECT ?4REJECT\
           ?>1REJECT ?>2REJECT ?>3REJECT ?>4REJECT\
           ?RSONOFF ?SETUP ?SOFTSTART ?SPLITFLOW\
           ?STDLEAK ?SYSPWD\
           ?TURBO ?TURBOHR ?VALVESTATE VER ?VOLUMEONOFF\
           WHYNOCAL ?0ENABLE SERVICE1 SERVICE2} {
puts "$c: [leak_ag cmd "$c"]"
}
