#!/usr/bin/tclsh

lappend auto_path ..
package require ParseOptions 2.0

set parsetable \
  [list {-f -format} fmt  {} {format}\
        {-d -descr}  desc {} {description}\
        -color       color red {color}]
if {[catch {parse_options "myprog" \
    $argv $parsetable} err]} { error $err }

puts "fmt:   $fmt"
puts "desc:  $desc"
puts "color: $color"



