#!/usr/bin/tclsh

lappend auto_path ..
package require xBlt

proc myprog {args} {
  set opts \
    [list {-f -format} fmt  {} {format}\
          {-d -descr}  desc {} {description}\
          -color       color red {color}]

  if {[catch {xblt::parse_options "myprog" \
      $args $opts} err]} { error $err }

  puts "fmt:   $fmt"
  puts "desc:  $desc"
  puts "color: $color"
}

myprog -f 1 -d descr -color blue

