#!/usr/bin/tclsh

lappend auto_path ..
package require ParseOptions 2.0

set opts \
  [list {-f -format} fmt  {} {format}\
        {-d -descr}  desc {} {description}\
        -color       color red {color}]

if {[catch {parse_options "myprog"\
    $argv $opts} err]} { error $err }

puts "fmt:   $fmt"
puts "desc:  $desc"
puts "color: $color"



