#!/usr/bin/tclsh

source ./spp_client.tcl
source ./spp_server.tcl
source ./device.tcl
source ./drivers.tcl
source ./chan.tcl
source ./locking.tcl

#Device lockin0
#puts [lockin0 cmd *IDN?]

#Device dgen0
#puts [dgen0 cmd *IDN?]

#Device ps0
#puts [ps0 cmd *IDN?]

#Device mult_ag
#puts [mult_ag cmd *IDN?]

Device db_local
db_local cmd "create test2 DOUBLE"

#Device osc0
#puts [osc0 cmd chan_set]

#Device ps0
#puts [ps0 cmd chan_set]



