# Tcl package index file
# This file is NOT generated by the "pkg_mkIndex" command 

set _name    Device
set _version 1.5
set _files   {spp_client spp_server device drivers chan locking}

set _pcmd {}
foreach _f $_files { lappend _pcmd "source [file join $dir $_f.tcl]" }
lappend _pcmd "package provide $_name $_version"
package ifneeded $_name $_version [join $_pcmd \n]

